name: thoriq_puki
version: 1.0.0+1
publish_to: none
description: Project Aplikasi Perpustakaan Digital UKK RPL 2024
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  date_time_picker: ^2.1.0
  art_sweetalert: ^0.0.5
  font_awesome_flutter: ^10.6.0
  flutter_onboarding_slider: ^1.0.11
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  email_validator: ^2.1.16
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  lottie: ^2.0.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter:
    sdk: flutter
  another_flutter_splash_screen: ^1.2.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  flutter_image_slideshow: ^0.1.6
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_aplikasi.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/logo/
    - assets/images/slider/
    - assets/images/konten/

